# Generated by Django 4.1.3 on 2022-11-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyecto_final', '0003_almacen_cargos_usuario_direccion_usuario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_ini', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_fin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proyecto_final.almacen')),
            ],
        ),
    ]
